export const BOARD_WIDTH = 10;
export const BOARD_HEIGHT = 20;
export const BLOCK_SIZE = 30;

export const GAME_SPEED = {
  INITIAL: 1000,
  MIN: 100,
  DECREASE_PER_LEVEL: 100,
};

export const SCORING = {
  LINE_CLEAR: 100,
  LINES_PER_LEVEL: 10,
  WORD_BASE: 200,
  WORD_LENGTH_MULTIPLIER: 1.5,
  COMBO_MULTIPLIER: 1.5,
  DIFFICULTY_BONUS_PER_LETTER: 50,
  LEVEL_MULTIPLIER: 0.1,
};
